### ISSUE TITLE
Refactor the way we handle methods for endpoints and for the returned instance

### ISSUE THREAD

**Issue by lazreg87** [BuiltonDev/javascript-sdk#37]
As part of our discussion on how to handle sorting and filtering better,
we came to the conclusion of separating more between endpoints that handle collections and the specific instances of such a collection. E.g.

**Payments:**
collection specific methods, like: 
get all payments, supporting filters and sort

**Payment instance**
instance specific methods, like:
update this instance
refresh this instance

**Comment by NicolasBonduel** [comment]
This will be handled in v3: https://github.com/BuiltonDev/javascript-sdk/pull/39
